### ISSUE TITLE
Cordova 2.3 compatibility?

### ISSUE THREAD

**Issue by cwarden** [phonegap-build/StatusBarPlugin#1]
Any suggestions on the changes that would be necessary to make this support 2.3.0?

**Comment by sectore** [comment]
@cwarden: Just a small typo? Cordova 3.2 instead of 2.3.

Anyway, a support of latest Cordova 3.2 would be great!

**Comment by cwarden** [comment]
@sectore, I'm actually still on 2.3.0.  We're using the the @forcedotcom mobile sdk, which includes two cordova plugins, but it's still based on cordova 2.3.0.

**Comment by wildabeast** [comment]
This plugin is specific to iOS 7, which isn't supported by 2.3.0 anyways I believe, so I think this is now moot. Closing.
