### ISSUE TITLE
Right portion of screen unresponsive to touch events

### ISSUE THREAD

**Issue by perqa** [phonegap-build/StatusBarPlugin#12]
I have tried the Status Bar plugin in combination with Phonegap Build, PG 3.1 and iOS7, but it doesn't seem to work properly. The app uses full-screen landscape view. 

I tried StatusBar.hide() in my deviceReady function, but the bar remained in view. And worse, the right-hand part of the screen became completely unresponsive to touch events. As if there was a transparent overlay on that part of the screen, possibly related to this bug: http://community.phonegap.com/nitobi/topics/inconsistent_ios_7_status_bar_build_problem. As described there, the overlay isn't transparent though, but it seems to cover exactly the same area that goes unresponsive in my case.

**Comment by wildabeast** [comment]
I believe this was another symptom of the problem in issue #4, and should be fixed in the latest version of the StatusBar Plugin (1.1.0).

**Comment by wildabeast** [comment]
Fixed in 1.1.0, closing.
