### ISSUE TITLE
fix for versions =< 3.1.0 explained

### ISSUE THREAD

**Issue by zeroshadow** [phonegap-build/StatusBarPlugin#13]
Download ZIP on your computer https://github.com/phonegap-build/StatusBarPlugin/archive/master.zip

open plugin.xml

change  version="3.1.0" to version=">=3.1.0"

then

$ phonegap local plugin add ~/Downloads/StatusBarPlugin

function sshide(){
                StatusBar.hide();
}

< body onLoad="sshide()" >

For me with 3.3.0 works

**Comment by bgbraga** [comment]
Thanks!!

**Comment by wildabeast** [comment]
This fix has been integrated.
