### ISSUE TITLE
overlaysWebView(false) causes viewport issue on ipad

### ISSUE THREAD

**Issue by tbassett44** [phonegap-build/StatusBarPlugin#15]
It seems that setting overlaysWebView to false causes the HTML of an application to be incorrectly sized (in iPad only).  The HTML content extends beyond the viewport.  Simply by changing to true and adjusting my html to account for this fixed my problem.  Seems like this is a bug though - figured I would comment because this drove me crazy for quite a while.

**Comment by bau720123** [comment]
+1

**Comment by otype** [comment]
+1

**Comment by davecurryco** [comment]
+1 - This issue means that the StatusBar plugin is a non-viable solution for our use case

**Comment by bau720123** [comment]
this plugin have been a lot of issue
such like this
https://github.com/phonegap-build/StatusBarPlugin/issues/4

**Comment by wildabeast** [comment]
Seems that the plugin does try to account for this [by changing the size of the viewport](https://github.com/phonegap-build/StatusBarPlugin/blob/master/src/ios/CDVStatusBar.m#L139) when setting the statusbar layout, but I guess its not working.

If any iOS gurus here know why that's not working, feel free to pipe in.

**Comment by wildabeast** [comment]
Fixed -- was an issue with our Cordova framework rather than this plugin itself.

**Comment by bau720123** [comment]
thanks @wildabeast 
so....maybe use the phonegap build 3.X (greater than 3.3，by future) with StatusBar 1.0.1 will solve the Most of problem?

**Comment by wildabeast** [comment]
Yes I made a change to the Cordova 3.3.0 framework on Build that appeared to have fixed this -- however it may have re-introduced other issues. Trying to sort this out.

**Edit**: might have to revert this change as it may have broken other things. Will likely be reopening this issue.

**Comment by bau720123** [comment]
thanks @wildabeast 
Fully understand

**Comment by joeltelling** [comment]
I think I have a fix here. Granted, this is my first comment ever on a github issue, so bear with me if I mess it all up.

in the CDVStatusBar.m file in the setStatusBarOverlaysWebView function there is an if/else - my else looks like this:

```
CGRect statusBarFrame = [UIApplication sharedApplication].statusBarFrame;
// bounds.origin.y = statusBarFrame.size.height;
// bounds.size.height -= statusBarFrame.size.height;

self.webView.clipsToBounds =YES;
self.webView.frame =  CGRectMake(0,statusBarFrame.size.height,self.webView.frame.size.width,self.webView.frame.size.height-statusBarFrame.size.height);

// self.webView.frame = bounds;
[self.webView.superview addSubview:_statusBarBackgroundView];
```

I know there is probably a better and more concise way of doing this, but it works for me. Phonegap 3.3 on iOS 7 iPhone 5 and iOS 6 iPhone 4. It seems the bounds stuff wasn't working right. I set the frame to what I knew would be good using the maths I had in my head. You guys give it a try too.

**Comment by wildabeast** [comment]
Awesome @joeltelling, will try this out asap.

FYI added some code formatting to your comment.

**Comment by joeltelling** [comment]
Awesome @wildabeast and thank you for adding formatting!

**Comment by wildabeast** [comment]
If its the same issue I was seeing, I actually found that removing `height=device-height` from the `<meta name="viewport" ... />` fixed this when the overlaysWebView was set to false...

**Comment by wildabeast** [comment]
Removing height=device-height from your meta viewport tag, and / or using the latest version of this plugin (1.1.0) should fix this. Closing.

**Comment by runspired** [comment]
@wildabeast this issue is not fixed in cordova 5

**Comment by runspired** [comment]
@wildabeast apologies, found this issue and wasn't paying enough attention, this is an issue with the official cordova plugin not the phonegap one in cordova 5.
