### ISSUE TITLE
UI problem when HideKeyboardFormAccessoryBar is true

### ISSUE THREAD

**Issue by YvonneYu** [phonegap-build/StatusBarPlugin#2]
Hello,

The issue is when I set HideKeyboardFormAccessoryBar as true in config.xml, the UI view will drop down 20px after I closed keyboard in iOS7.

Thanks for awesome plugin.

**Comment by wildabeast** [comment]
Not sure if this is still an issue for you since its 4 months old ... but if you still care:

This plugin is only supported by PhoneGap 3.1.0 and above, and the HideKeyboardFormAccessoryBar preference was deprecated in 3.1.0 ... what version of PhoneGap are you using, and are you building locally?

**Comment by wildabeast** [comment]
Closing re: comment above.
