### ISSUE TITLE
StatusBar.isVisible issues

### ISSUE THREAD

**Issue by bau720123** [phonegap-build/StatusBarPlugin#22]
I am using PGB 3.3 with your latest plugin 1.10 and my ipad mini 7.0.6

when I use this method to show or hide the status bar and detect the statusbar is visible or not

```
StatusBar.show(); //the status bar is indeed show up
alert(StatusBar.isVisible);
```

it will alert "true" (good)

but...

```
StatusBar.hide(); //the status bar is indeed hidden
alert(StatusBar.isVisible);
```

it will still alert "true" (but I think it should be false in this situation)

**Comment by bau720123** [comment]
hi @wildabeast 
is there any update information or....
tks~

**Comment by bau720123** [comment]
hi @wildabeast 
anything update?

**Comment by wildabeast** [comment]
@bau720123 I haven't had time to look at this issue sorry -- you should be able to track this visibility in a variable yourself though I think.

**Comment by bau720123** [comment]
thanks @wildabeast 
got it and close this article by myself

**Comment by wildabeast** [comment]
This is still a bug though right? If so please leave it open ... hopefully we can get to it soon.

**Comment by bau720123** [comment]
got it~
I will check it out again and maybe feedback some information for you
tks @wildabeast

**Comment by bau720123** [comment]
hi @wildabeast 
I made a detail test

situation A
if I add this plugin
https://build.phonegap.com/plugins/641
and your latest plugin
https://build.phonegap.com/plugins/505

```
StatusBar.show(); //the status bar is indeed show up
alert(StatusBar.isVisible);
```

it will alert "true" (good)

```
StatusBar.hide(); //the status bar is indeed hidden
alert(StatusBar.isVisible);
```

it will alert "false" (good)

situation B
if I only add your latest plugin
https://build.phonegap.com/plugins/505

```
StatusBar.show(); //the status bar is indeed show up
alert(StatusBar.isVisible);
```

it will alert "true" (good)

```
StatusBar.hide(); //the status bar is indeed hidden
alert(StatusBar.isVisible);
```

it will still alert "true" (not correct)

I just guess，maybe this plugin
https://build.phonegap.com/plugins/641
let something setting to "Initialization"，so...after "Initialization"，the "isVisible" method become normal
otherwise
the "isVisible" still incorrect
just check out the info.plist
http://www.littlebau.com/status_ios.gif

[finally]~
In order to prove that I was right

first，I remove this plugin first
https://build.phonegap.com/plugins/641

second
I use this code in my config.xml

```
<gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance" overwrite="true">
<false/>
</gap:config-file>
```

third，rebuild and reinstall

success~

```
StatusBar.show(); //the status bar is indeed show up
alert(StatusBar.isVisible);
```

it will alert "true" (good)

```
StatusBar.hide(); //the status bar is indeed hidden
alert(StatusBar.isVisible);
```

it will alert "false" (good)
