### ISSUE TITLE
Plugin doesn't seem to work

### ISSUE THREAD

**Issue by vespino** [phonegap-build/StatusBarPlugin#25]
I have tried the following integration (Phonegap Build):

In my config.xml:

[gap:plugin name="com.phonegap.plugin.statusbar" /]
[preference name="StatusBarOverlaysWebView" value="true" /](tried false and true)
[preference name="StatusBarBackgroundColor" value="#111111" /]

I also tried:

function onDeviceReady() {
    app.initialize();
    StatusBar.overlaysWebView(true);
    StatusBar.backgroundColorByHexString("#111111");
}

Everything results in the standard status bar color. I'm I doing something wrong?

**Comment by wildabeast** [comment]
Firstly, go to the details page of your PhoneGap Build app, and ensure version 1.1.0 of the plugin is included under Plugins.

Second, the StatusBarOverlaysWebView and StatusBarBackgroundColor preferences are not supported by PhoneGap Build, [as mentioned in the README](https://github.com/phonegap-build/StatusBarPlugin#preferences).

Have you tried wrapping your call in a try/catch to see if it throws an exception?

Lastly, you can give me your PhoneGap Build App ID and I can have a look at your app if you'd like.

**Comment by vespino** [comment]
The plugin is included. I now have the following in my device ready function and the status bar is black with white text:

StatusBar.overlaysWebView(true);
StatusBar.backgroundColorByHexString("#1d617f");

My PhoneGap Build ID is 769083.

**Comment by vespino** [comment]
I have now tried StatusBar.overlaysWebView(false); which gives the same result, black status bar, white text.

**Comment by wildabeast** [comment]
Are you sure your code is making it to those calls? I just had a look at your app, and tried the following:

```
function onDeviceReady() {
    app.initialize();
    alert('hi');
    StatusBar.overlaysWebView(false);
    StatusBar.backgroundColorByHexString("#1d617f");
}
```

and the alert never appears.

_Side note_:
Setting the overlaysWebView to true hides the background bar, so there is no point in setting it to true (hiding the background bar) and then changing the background color.

**Comment by wildabeast** [comment]
I also tried connecting the Safari debugger after launching, and running
`StatusBar.backgroundColorByHexString("#1d617f");`
and the color successfully changed.

**Comment by vespino** [comment]
You are the man! I moved the statusbar items and now the statusbar is blue!

Don't know what causes the problem, but I now know that the initialize should always be at the bottom.

Thanks!

**Comment by wildabeast** [comment]
np.

PS the fact that the initialize method never returns is a bad sign ... there's an exception somewhere...

**Comment by vespino** [comment]
I will check, the initialize function seems to do what it is supposed to do, that makes it extra strange.
