### ISSUE TITLE
Blank status bar appears after InAppBrowser closed

### ISSUE THREAD

**Issue by maxmoore14** [phonegap-build/StatusBarPlugin#3]
To reproduce:
1. add plugins for both StatusBar and InAppBrowser
2. call StatusBar.hide()
3. call window.open(some_url, '_blank')
4. press "Done"
5. there is now a blank status bar - by blank I mean none of the actual status info is visible, just a blank bar

I'm testing on a physical iPhone 5 with iOS 7.

**Comment by maxmoore14** [comment]
The same behavior occurs after accessing the camera roll with a file input.

Hide the status bar, tap the file input to open the camera roll, choose images or not (doesn't matter). When control is transferred back to the app, a blank status bar is at the top.

**Comment by bau720123** [comment]
I run
StatusBar.hide(); window.open(encodeURI('http://apache.org'), '_blank', 'location=yes,closebuttoncaption=done');
but there is no blank status bar，I'm testing on a physical iPad mini with iOS 7.04

As you said the "camera" problem，I have not tested it

still care about your issue

**Comment by lxw185** [comment]
I have the same issue. It happens after selecting files in file input. UIStatusBarStyleLightContent is set, and a black background in status bar is also set in my case. What happens, I believe, is the status bar style changed back to default(black) for some reason, so it's not visible on the black background.

**Comment by wildabeast** [comment]
Having trouble reproducing this one. If someone could share their PhoneGap Build App ID for an app that demos thie issue it would be appreciated.

Also try out the updated version of the StatusBar Plugin (1.1.0) and see if it still occurs there.

**Comment by bau720123** [comment]
I Try out version 1.1.0 on PhoneGap Build，problem was fixed
Thanks @wildabeast

**Comment by wildabeast** [comment]
Thanks.
