### ISSUE TITLE
Not working on iOS 7.1 64bit

### ISSUE THREAD

**Issue by dkazubek** [phonegap-build/StatusBarPlugin#30]
I am using this plugin in my Cordova 3.3.1 project. When I try to run it on my iOS 7.1 64 bit iPhone I am getting an error when this function is called:
- (void) _ready:(CDVInvokedUrlCommand*)command
  {
  // set the initial value
  [self.commandDelegate evalJs:[NSString stringWithFormat:@"StatusBar.isVisible = %@;", [UIApplication sharedApplication].statusBarHidden? @"false" : @"true" ]];
  }

It complains that the command parameter is nil. When I go back to the calling code:
- (BOOL)execute:(CDVInvokedUrlCommand*)command
  {
  ...
      objc_msgSend(obj, normalSelector, command);
  ...
  }

the command here is not nil.

It works fine in the 64 bit emulator. It only seems to crash on a device.

**Comment by Odi55555** [comment]
I have the same issue on an iPhone 5s with iOS 7.1. I'm using phonegap 3.4.0-0.19.13 which uses cordova 3.4.0-0.1.3

**Comment by sngahane** [comment]
It's a known problem of Cordova when working with plugins and 64-bit devices.
By patching two Cordova files, we succeeded to make it work using [this tutorial](http://shazronatadobe.wordpress.com/category/cordova/) (see issue 1).

**Comment by Odi55555** [comment]
Yeah thanks I tried that, but maybe I missed something... Everything works fine with cordova 3.4.1-0.1.0
This issue can be closed.

**Comment by dkazubek** [comment]
I have applied the changes from the suggested tutorial and everything works fine for me. The issue can be closed. Thanks.

**Comment by wildabeast** [comment]
As mentioned, issue with Cordova, not this particular plugin. Closing.
