### ISSUE TITLE
How do I set StatusBarBackgroundColor in config.xml?

### ISSUE THREAD

**Issue by boozedog** [phonegap-build/StatusBarPlugin#7]
Thanks!

**Comment by bau720123** [comment]
it should be no way to set in config.xml
the only way is set to the javascript
StatusBar.backgroundColorByName("red")
OR
StatusBar.backgroundColorByHexString("#C0C0C0");

**Comment by boozedog** [comment]
That's sad. I used to be able to do it in PhoneGap 2.9.0 !

**Comment by bau720123** [comment]
Asked the author or just wait...ㄚ_ㄚ

**Comment by bau720123** [comment]
try this in your config.xml
it is the only way similar you want it
https://build.phonegap.com/docs/config-xml

preference name="ios-statusbarstyle" value="black-opaque" /> //default is the grey color，or you can set black-opaque or black-translucent

**Comment by boozedog** [comment]
Already got that in there. Works fine with 2.9.0 but seems to be ignored in 3.1.0 ...

**Comment by boozedog** [comment]
Hey there Bob any ideas?

**Comment by boozedog** [comment]
Or is there maybe another project I should enter this issue under!

**Comment by bobeasterday** [comment]
@bau720123 has it right. Have you tried setting the bg color with the plugin?

**Comment by boozedog** [comment]
Thanks! Here's what I have in my config.xml:

<preference name="ios-statusbarstyle" value="black-opaque" />

For some reason, it seems to get ignored when I use v3.1.0 . Works fine in v2.9.0 .

**Comment by bobeasterday** [comment]
@boozedog - iOS 7 changes pretty much everything . Use the status bar plugin to set the bg color of the status bar, not config.xml.

**Comment by boozedog** [comment]
Don't suppose the plugin can be changed to allow use of existing config.xml values?

**Comment by bobeasterday** [comment]
Not in the short term. When we add support for Cordova 3.2 we'll probably revisit it. 3.2 defaults to iOS7 behavior (status bar overlaps webview). In that case, the status bar plugin will likely be required if you want iOS6 behavior. We'll evaluate how the status bar plugin interacts with config.xml at that time. No idea yet when 3.2 support will be added to Build.

**Comment by boozedog** [comment]
OK understood. Just to be clear, though, iOS6 and iOS7 behavior is consistent as long as I use 2.9.0 . It's 3.1.0 that causes the app to look and feel different in iOS6 vs. 7 ...

**Comment by bobeasterday** [comment]
2.9.0 builds against the iOS6 SDK, so I wouldn't expect any difference in behavior as you are still running an iOS6 app even if your device has been updated to iOS7.

3.1.0 builds against the iOS7 SDK which has substantial changes to UI behavior, not the least of which is how the status bar is managed.

**Comment by boozedog** [comment]
Ah of course. That makes sense. Thanks for the help Bob.
