### ISSUE TITLE
overlaysWebView setting forgotten after phone call notification bar

### ISSUE THREAD

**Issue by anaoum** [phonegap-build/StatusBarPlugin#9]
To reproduce:

StatusBar.overlaysWebView(true);

receive phone call, open app, green bar is there

end phone call, go back to app, the status bar is no longer overlaying the web view.

This is not happening in the simulator, only on a device. Any ideas?

**Comment by bobeasterday** [comment]
@anaoum I have verified your issue and hope to have a solution deployed later today.

**Comment by wildabeast** [comment]
This was fixed by @bobeast.
